//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MobileDevice()
        {
            this.Comment = new HashSet<Comment>();
            this.LapTopGpu = new HashSet<LapTopGpu>();
            this.MobileDeviceReview = new HashSet<MobileDeviceReview>();
            this.MobileDeviceColor = new HashSet<MobileDeviceColor>();
            this.MobileDeviceCC = new HashSet<MobileDeviceCC>();
            this.MobileDeviceOther = new HashSet<MobileDeviceOther>();
            this.MobileDeviceMutimedia = new HashSet<MobileDeviceMutimedia>();
            this.PTSensor = new HashSet<PTSensor>();
            this.SMD = new HashSet<SMD>();
            this.Storage = new HashSet<Storage>();
        }
    
        public string MD_ { get; set; }
        public string MDName { get; set; }
        public string MDType { get; set; }
        public string OfficialWebsite { get; set; }
        public string OS { get; set; }
        public string Weight { get; set; }
        public string Size { get; set; }
        public string Battery { get; set; }
        public string Warranty { get; set; }
        public string Ram { get; set; }
        public string ImageURL { get; set; }
        public string Screen_ { get; set; }
        public string ManuName { get; set; }
        public string Series_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual LapTop LapTop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LapTopGpu> LapTopGpu { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual Series Series { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDeviceReview> MobileDeviceReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDeviceColor> MobileDeviceColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDeviceCC> MobileDeviceCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDeviceOther> MobileDeviceOther { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDeviceMutimedia> MobileDeviceMutimedia { get; set; }
        public virtual PhoneAndTablet PhoneAndTablet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PTSensor> PTSensor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMD> SMD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage> Storage { get; set; }
    }
}
