//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileDeviceSpecEntities : DbContext
    {
        public MobileDeviceSpecEntities()
            : base("name=MobileDeviceSpecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArmSoc> ArmSoc { get; set; }
        public virtual DbSet<Camera> Camera { get; set; }
        public virtual DbSet<CameraOther> CameraOther { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<GPU> GPU { get; set; }
        public virtual DbSet<LapTop> LapTop { get; set; }
        public virtual DbSet<LapTopGpu> LapTopGpu { get; set; }
        public virtual DbSet<Manufacture> Manufacture { get; set; }
        public virtual DbSet<ManufacturePosition> ManufacturePosition { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MobileDevice> MobileDevice { get; set; }
        public virtual DbSet<MobileDeviceCC> MobileDeviceCC { get; set; }
        public virtual DbSet<MobileDeviceColor> MobileDeviceColor { get; set; }
        public virtual DbSet<MobileDeviceMutimedia> MobileDeviceMutimedia { get; set; }
        public virtual DbSet<MobileDeviceOther> MobileDeviceOther { get; set; }
        public virtual DbSet<MobileDeviceReview> MobileDeviceReview { get; set; }
        public virtual DbSet<PhoneAndTablet> PhoneAndTablet { get; set; }
        public virtual DbSet<PTSensor> PTSensor { get; set; }
        public virtual DbSet<Screen> Screen { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<SMD> SMD { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<StorePosition> StorePosition { get; set; }
        public virtual DbSet<x86CPU> x86CPU { get; set; }
    }
}
