//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneAndTablet
    {
        public string MD_ { get; set; }
        public string WAndDProof { get; set; }
        public string DualSim { get; set; }
        public string InStorage { get; set; }
        public string ExStorage { get; set; }
        public string SocName { get; set; }
        public string SocManuName { get; set; }
        public string Camera_ { get; set; }
    
        public virtual ArmSoc ArmSoc { get; set; }
        public virtual Camera Camera { get; set; }
        public virtual MobileDevice MobileDevice { get; set; }
    }
}
